# These are supported funding model platforms
buy_me_a_coffee: tomtyiu
patreon: https://patreon.com/LegolasYiu?utm_medium=unknown&utm_source=join_link&utm_campaign=creatorshare_creator&utm_content=copyLink
